name: switchyomega
dependencies:
  browser: any
  crypto: any
  json: any
  polymer: '>=0.9.1 <0.10.0'
  grinder: any
  yaml: any
  path: any
transformers:
- polymer:
    entry_points:
    - web/options/options.html
    - web/background/background.html
    csp: true
